spring:
  application:
    name: spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
server:
  port: 8766
ribbon:
  okhttp:
    enabled: true
  restclient:
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
feign:
  hystrix:
    enabled: true